spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daitong?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver - class - name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG